vich_uploader:
    db_driver: orm # or mongodb or phpc

    metadata:
        type: attribute

    mappings:
        event_thumbnail:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update:   true # Delete the old file when a new file is uploaded
            delete_on_remove:   true # Delete the file when the entity is removed